services:
  - type: web
    name: online-greenhome
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ALLOWED_CHAT_IDS
        sync: false
      - key: API_SECRET
        sync: false
